version: "3.9"
services:
  database:
    image: ${DB_IMAGE}:${DB_TAG}
    container_name: ${DB_CONTAINER_NAME}
    networks:
      - database
    volumes:
      - ${DB_DATA_PATH}:/data/db:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s

  backend:
    build:
      context: ./back
      dockerfile: dockerfile
      target: ${BACK_TARGET}
      args:
        - BASE_IMAGE=${BACK_BASE_IMAGE}
        - BASE_TAG=${BACK_BASE_TAG}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - CONTAINER_NAME=${BACK_CONTAINER_NAME}
        - COMMAND=${BACK_CMD}
    image: ${BACK_IMAGE}:${BACK_TAG}
    container_name: ${BACK_CONTAINER_NAME}
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MUD_PEPPER=${MUD_PEPPER}
      - ANAL_HOST=${ANAL_HOST}
      - ANAL_PORT=${ANAL_PORT}
    networks:
      - database
      - application
    volumes:
      - ${LOG_PATH}:/mnt/logs:rw
    deploy:
      # resources:
      #   limits:
      #     cpus: ${BACK_CPU_LIMIT}
      #     memory: ${BACK_MEM_LIMIT}
      #   reservations:
      #     cpus: ${BACK_CPU_RESERV}
      #     memory: ${BACK_MEM_RESERV}
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s

  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
      args:
        - BASE_IMAGE=${FRONT_BASE_IMAGE}
        - BASE_TAG=${FRONT_BASE_TAG}
        - CONTAINER_NAME=${FRONT_CONTAINER_NAME}
        - COMMAND=${FRONT_CMD}
    image: ${FRONT_IMAGE}:${FRONT_TAG}
    container_name: ${FRONT_CONTAINER_NAME}
    environment:
      - PORT=${FRONT_PORT}
      - API_DOMAIN=${API_DOMAIN}
      - API_PORT=${API_PORT}
    networks:
      - application
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - ${LOG_PATH}:/mnt/logs:rw
    deploy:
      # resources:
      #   limits:
      #     cpus: ${FRONT_CPU_LIMIT}
      #     memory: ${FRONT_MEM_LIMIT}
      #   reservations:
      #     cpus: ${FRONT_CPU_RESERV}
      #     memory: ${FRONT_MEM_RESERV}
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s

networks:
  database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
  application:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.2.0/24
