version: "3.9"
services:
  backend:
    build:
      context: ./back
      dockerfile: dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE_BACK}
        - BASE_TAG=${BASE_TAG_BACK}
        - COPY_DIR=backend
        - COMMAND=${COMMAND_BACK}
        - CONTAINER_NAME=${CONTAINER_NAME_BACK}
    image: ${IMAGE_BACK}:${TAG_BACK}
    depends_on:
      - database
    container_name: ${CONTAINER_NAME_BACK}
    environment:
      - PORT=${PORT_BACK}
      - NODE_ENV
      - MONGO_HOST=${CONTAINER_NAME_DB}
      - MONGO_PORT=27017
      - TARGET_DB
    networks:
      - mud
    volumes:
      - ${LOG_VOLUME_BACK}:/mnt/logs:rw
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT_BACK}
          memory: ${MEM_LIMIT_BACK}
        reservations:
          cpus: ${CPU_RESERV_BACK}
          memory: ${MEM_RESERV_BACK}
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s
    secrets:
      - mongo_username
      - mongo_password

  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE_FRONT}
        - BASE_TAG=${BASE_TAG_FRONT}
        - COPY_DIR=frontend
        - COMMAND=${COMMAND_FRONT}
        - CONTAINER_NAME=${CONTAINER_NAME_FRONT}
    image: ${IMAGE_FRONT}:${TAG_FRONT}
    container_name: ${CONTAINER_NAME_FRONT}
    environment:
      - PORT=${PORT_FRONT}
      - REACT_APP_BACKEND_URL=http://${DOMAIN}:${PORT_PROXY}/api
    networks:
      - mud
    volumes:
      - ${LOG_VOLUME_FRONT}:/mnt/logs:rw
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT_FRONT}
          memory: ${MEM_LIMIT_FRONT}
        reservations:
          cpus: ${CPU_RESERV_FRONT}
          memory: ${MEM_RESERV_FRONT}
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s

networks:
  mud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24

secrets:
  mongo_username:
    file: ./secrets/mongo_username
  mongo_password:
    file: ./secrets/mongo_password
