#!/usr/bin/env python3
# coding=utf-8

# How to use
# You need to set environment variables in advance for database connection.
# ex) source ../env/env.local.sh

# py demo_money_gen <username> <input data scale>
# ex) py demo_money_gen demouser 3000

import os, sys, random

username = sys.argv[1]
scale = int(sys.argv[2])
tags_arrange = ['foo', 'bar', 'baz', 'kim', 'dev']
filename = 'demo_money_insert.js'
db_username = os.getenv('DB_USERNAME')
db_password = os.getenv('DB_PASSWORD')
db_host = os.getenv('DB_HOST')
db_port = os.getenv('DB_PORT')
mongo_url = f'mongodb://{db_username}:{db_password}@{db_host}:{db_port}/mud?authSource=admin' if len(db_username) > 0 and len(db_password) > 0 else f'mongodb://{db_host}:{db_port}/mud'
collname = 'money'

def gen_date_str():
    year = '2021'
    month = random.randint(1, 12)
    if month == 2:
        date = random.randint(1, 28)
    elif month in [1, 3, 5, 7, 8, 10, 12]:
        date = random.randint(1, 31)
    else:
        date = random.randint(1, 30)
    return f"new Date('{year}-{month}-{date}')"

def gen_amount_str():
    if random.randint(1, 100) > 95:
        amount = random.randint(300000, 500000)
    else:
        amount = random.randint(-30000, -1000)
    return amount

def gen_tags_str():
    tags = []
    for i in range(len(tags_arrange)):
        if random.randint(0, 1) == 1:
            tags.append(tags_arrange[i])
    
    tags_str = ''
    if len(tags) > 0:
        tags_str = "['" + '\',\''.join(tags) + "']"
    else:
        tags_str = '[]'
    return tags_str

with open(filename, 'w', encoding='utf-8') as file:
    file.write('const moneyList = [\n')
    for i in range(scale):
        file.write(f"  {{username: '{username}', date: {gen_date_str()}, amount: {gen_amount_str()}, summary: '', tags: {gen_tags_str()}, maketime: new Date()}},\n")
    file.write(']\n')
    file.write(f"db.{collname}.insertMany(moneyList)\n")

os.system(f"mongo {mongo_url} {filename}")
