#!/bin/bash

wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
sudo echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
