#!/bin/bash

sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo amazon-linux-extras install java-openjdk11
sudo amazon-linux-extras install epel
sudo yum install epel-release
sudo yum install jenkins
sudo systemctl start jenkins
sudo gpasswd -a jenkins docker
